export const plan = [
  {
    id: "1",
    id_sl: "16-а00134",
    id_object: "1",
    id_vid_rabot: "21",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "5",
    st_brigadi: "5",
    avto: "5",
    vipolneno: "0",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "все хорошо",
    id_gn: "5",
    opasn: "1",
    utv_auto: "1",
    utv_opasn: "0",
  },
  {
    id: "2",
    id_sl: "16-а00135",
    id_object: "19",
    id_vid_rabot: "7",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "3",
    st_brigadi: "3",
    avto: "2",
    vipolneno: "1",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "хорошо",
    id_gn: "2",
    opasn: "1",
    utv_auto: "1",
    utv_opasn: "1",
  },
  {
    id: "3",
    id_sl: "16-а00134",
    id_object: "1",
    id_vid_rabot: "21",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "5",
    st_brigadi: "5",
    avto: "5",
    vipolneno: "0",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "все хорошо",
    id_gn: "5",
    opasn: "0",
    utv_auto: "1",
    utv_opasn: "0",
  },
  {
    id: "4",
    id_sl: "16-а00134",
    id_object: "1",
    id_vid_rabot: "21",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "5",
    st_brigadi: "5",
    avto: "5",
    vipolneno: "0",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "все хорошо",
    id_gn: "5",
    opasn: "0",
    utv_auto: "1",
    utv_opasn: "0",
  },
  {
    id: "5",
    id_sl: "16-а00134",
    id_object: "1",
    id_vid_rabot: "21",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "5",
    st_brigadi: "5",
    avto: "5",
    vipolneno: "0",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "все хорошо",
    id_gn: "5",
    opasn: "0",
    utv_auto: "1",
    utv_opasn: "0",
  },
  {
    id: "6",
    id_sl: "16-а00134",
    id_object: "1",
    id_vid_rabot: "21",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "5",
    st_brigadi: "5",
    avto: "5",
    vipolneno: "0",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "все хорошо",
    id_gn: "5",
    opasn: "0",
    utv_auto: "1",
    utv_opasn: "0",
  },
  {
    id: "7",
    id_sl: "16-а00134",
    id_object: "1",
    id_vid_rabot: "21",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "5",
    st_brigadi: "5",
    avto: "5",
    vipolneno: "0",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "все хорошо",
    id_gn: "5",
    opasn: "0",
    utv_auto: "1",
    utv_opasn: "0",
  },
  {
    id: "8",
    id_sl: "16-а00134",
    id_object: "1",
    id_vid_rabot: "21",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "5",
    st_brigadi: "5",
    avto: "5",
    vipolneno: "0",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "все хорошо",
    id_gn: "5",
    opasn: "0",
    utv_auto: "1",
    utv_opasn: "0",
  },
  {
    id: "9",
    id_sl: "16-а00134",
    id_object: "1",
    id_vid_rabot: "21",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "5",
    st_brigadi: "5",
    avto: "5",
    vipolneno: "0",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "все хорошо",
    id_gn: "5",
    opasn: "0",
    utv_auto: "1",
    utv_opasn: "0",
  },
  {
    id: "10",
    id_sl: "16-а00134",
    id_object: "1",
    id_vid_rabot: "21",
    id_prdr_org: "",
    sposob: "ss",
    brigada: "5",
    st_brigadi: "5",
    avto: "5",
    vipolneno: "0",
    prochina_nevipol: "нет времени",
    data_rabot: "2022-11-18",
    comment: "все хорошо",
    id_gn: "5",
    opasn: "0",
    utv_auto: "1",
    utv_opasn: "0",
  },
];
const fetchAll = () =>
  new Promise((resolve) => {
    window.setTimeout(function () {
      resolve(plan);
    }, 2000);
  });

export default {
  fetchAll,
};
